Repository octopi-digital/optimalmd-server, pull requests merged in 2024-12, with the labels that each got.

#19 error handling
  controller/authController.js
  controller/getLyricController.js
  controller/rxvaletController.js
Labels: bug, enhancement

#40 Fa/plan upgrade and dynamic plan 36
  controller/couponController.js
  controller/dependentController.js
  controller/planController.js
  model/planSchema.js
  router/couponRoutes.js
Labels: enhancement

#43 update dependent route and schema
  controller/couponController.js
  controller/dependentController.js
  controller/paymentController.js
  model/dependentSchema.js
  router/dependentRoutes.js
Labels: enhancement

#45 fixed update dependent
  controller/authController.js
  controller/dependentController.js
Labels: bug

#48 updated plan schema
  model/planSchema.js
Labels: enhancement

#54 solve dependent existing email issue
  controller/dependentController.js
  model/dependentSchema.js
Labels: enhancement
